// Recipes
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES'

// Navigation
export const SET_TAB = 'SET_TAB'

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'

export const ADD_RECIPE = 'ADD_RECIPE'

export const INCREMENT_BLUEJELLYBEANS = 'INCREMENT_BLUEJELLYBEANS'
export const INCREMENT_PINKJELLYBEANS = 'INCREMENT_PINKJELLYBEANS'
export const INCREMENT_ORANGEJELLYBEANS = 'INCREMENT_ORANGEJELLYBEANS'
export const INCREMENT_YELLOWJELLYBEANS = 'INCREMENT_YELLOWJELLYBEANS'
export const INCREMENT_PURPLEJELLYBEANS = 'INCREMENT_PURPLEJELLYBEANS'
export const INCREMENT_GREENJELLYBEANS = 'INCREMENT_GREENJELLYBEANS'
export const INCREMENT_REDJELLYBEANS = 'INCREMENT_REDJELLYBEANS'
